import { useState } from 'react'
import { motion } from 'framer-motion'

export default function ClinicalNote({ note }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(note)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  if (!note) return null

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.7, duration: 0.5 }}
      className="bg-slate-800/50 rounded-2xl border border-slate-700 p-8"
    >
      <h3 className="text-2xl font-bold text-white mb-4">
        ✍️ Generated Clinical Note
      </h3>

      <p className="text-sm text-slate-400 mb-4">
        Ready-to-copy documentation for your patient's medical record:
      </p>

      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.8 }}
        className="bg-slate-900/50 border-2 border-slate-700 rounded-lg p-6 mb-6"
      >
        <p className="text-slate-200 leading-relaxed whitespace-pre-wrap font-mono text-sm">
          {note}
        </p>
      </motion.div>

      <motion.button
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.85 }}
        onClick={handleCopy}
        className={`w-full py-3 font-semibold rounded-lg transition ${
          copied
            ? 'bg-indigo-600 text-white'
            : 'bg-indigo-600 text-white hover:bg-indigo-700 transform hover:-translate-y-0.5'
        }`}
      >
        {copied ? '✅ Copied to Clipboard!' : '📋 Copy to Clipboard'}
      </motion.button>

      <p className="text-xs text-slate-400 mt-4 text-center">
        Note generated by Claude AI • For documentation purposes • Clinical judgment required
      </p>
    </motion.div>
  )
}
